title: "Zagarsuren Sukhbaatar"
author: "Zagarsuren Sukhbaatar"
description: "Master of AI at UTS (Aug 2023 - May 2025')" 

github_username: zagarsuren 
linkedin_username: zagarsuren
#facebook_username: username
#instagram_username: username
#youtube_username: username

#########################################################################################
theme: "minima"

# rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: false
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge